# -------------------------------------------------------------------------
# choose your compiler (must be ANSI-compliant!) and linker command, plus
# any additionally needed flags

CC = gcc
LD = gcc
CFLAGS = -O3 -fomit-frame-pointer -Wall
LDFLAGS =

TARG_OBJEXTENSION = .o
TARG_EXEXTENSION =

HOST_OBJEXTENSION = $(TARG_OBJEXTENSION)
HOST_EXEXTENSION = $(TARG_EXEXTENSION)

# -------------------------------------------------------------------------
# directories where binaries, includes, and manpages should go during
# installation

BINDIR = /usr/bin
INCDIR = /usr/include/asl
MANDIR = /usr/share/man
LIBDIR = /usr/lib/asl
DOCDIR = /usr/share/doc/asl

# -------------------------------------------------------------------------
# character encoding to use (choose one of them)

# CHARSET = CHARSET_ASCII7
# CHARSET = CHARSET_IBM437
# CHARSET = CHARSET_ISO8859_1
CHARSET = CHARSET_UTF8
